### PR TITLE
Add option to disable contents table output

### PR DESCRIPTION
**Pull request by spacedawwwg**

### CODE REVIEW

**Comment by andrewbrandwood** [comment]
Hey man, 

Happy to pull this in. You seem to have skipped a version.  Could you update the version number to 0.3.0 then I will merge it in.

**Comment by spacedawwwg** [comment]
It wasn't skipped, I had two go's at adding it -  [v0.3.0](https://github.com/andrewbrandwood/gulp-sass-generate-contents/pull/5/commits/54bf428182e0d22803f50b0e48371f1c08bf4ab5) was a scruffy quick fix, then [v0.4.0](https://github.com/andrewbrandwood/gulp-sass-generate-contents/pull/5/commits/78c54872f351a57e76d586c43723b75ac3759be0) for the second cleaned up attempt with tests.

Happy to change it to to 0.3.0 if you like - it just might seem a little confusing if the versions in the source code change

**Comment by andrewbrandwood** [comment]
If it's the same feature but a code re-factor or a bug fix then it should have been a patch release so 0.3.1

No bother. I'll merge this one and add some documentation on contributing :)

**Comment by spacedawwwg** [comment]
Ah, ok! I'll correct it to 0.3.1 in a new pull request!

**Pull request merged**
